# fly.toml app configuration file generated for shipping-and-logistic on 2025-10-25T07:19:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'shipping-and-logistic'
primary_region = 'iad'
console_command = '/rails/bin/rails console'

[build]

[env]
  PORT = '8080'

[processes]
  app = './bin/rake litestream:run ./bin/rails server'
  sidekiq = 'bundle exec sidekiq'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
