default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PGUSER") { "felix" } %>
  password: <%= ENV.fetch("PGPASSWORD") { "Felix@066" } %>
  host: <%= ENV.fetch("PGHOST") { "localhost" } %>
  port: <%= ENV.fetch("PGPORT") { 5432 } %>

development:
  <<: *default
  database: shipping_development

test:
  <<: *default
  database: shipping_test
production:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


