Rails.application.routes.draw do
  # === Devise / ActiveAdmin ===
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users

  # Role switching
  post "toggle_role",   to: "users#toggle_role",   as: :toggle_role
  post "become_seller", to: "users#become_seller", as: :become_seller
  post "become_buyer",  to: "users#become_buyer",  as: :become_buyer

  # Seller onboarding form
  get "seller/new", to: "users#new_seller", as: :new_seller

  # === My Account (Profile / Storefront settings) ===
  resource :account, only: [:show, :update], controller: "users" do
    get "/",   to: "users#account",        as: ""
    patch "/", to: "users#update_account"
  end

  # === Products and nested resources (slug-based) ===
  resources :products, param: :slug do
    resources :orders, only: [:new, :create]

    resources :reviews, only: [:create, :edit, :update, :destroy, :show] do
      post :vote, on: :member
      resources :reports, only: [:new, :create]
    end

    resources :variants,    only: [:new, :create, :edit, :update, :destroy]
    resources :inventories, only: [:new, :create, :edit, :update, :destroy]

    member do
      # Image management
      post   :upload_additional_images
      delete :delete_additional_image
      post   :bulk_inventory_upload
      delete :delete_image

      # Turbo-friendly custom actions
      post   :add_variant
      delete :remove_variant
      delete :remove_variant_image
      delete :remove_gallery
      post   :add_variant_image
    end

    # Legacy gallery image route
    delete "gallery_images/:image_id",
           to: "products#remove_gallery_image",
           as: :remove_gallery_image
  end

  # === M-PESA Callback ===
  post "/mpesa/callback/:order_id", to: "payments#mpesa_callback", as: :mpesa_callback

  # Currency
  post "set_currency", to: "currencies#set", as: :set_currency

  # === Orders and nested payment/shipment routes ===
  resources :orders, only: [:index, :show, :new, :create] do
    resources :order_items, only: [:create, :destroy]

    resources :payments, only: [:create] do
      collection do
        match :paystack_callback, via: [:get, :post]
        match :paypal_callback,   via: [:get, :post]
      end
    end

    resource :shipment, only: [:new, :create, :show, :edit, :update] do
      post :track, on: :member
    end

    resources :notifications, only: [:index]
    member do
      get :receipt
    end
  end

  # === Other resources ===
  resources :shipments, only: [:index]
  resources :messages, only: [:index, :create]
  resources :notifications, only: [:index] do
    patch :mark_read, on: :member
  end

  # Sellers (slug-based)
  resources :sellers, only: [:show, :edit, :update], param: :slug do
    get :subcategories, on: :member
  end

  resources :discounts, only: [:new, :create, :edit, :update, :destroy]
  resources :product_images, only: [:destroy]

  # Categories
  resources :categories do
    get :subcategories, on: :member
  end

  # === Dashboards and Cart ===
  get "dashboard/buyer",  to: "dashboards#buyer",  as: :buyer_dashboard
  get "dashboard/seller", to: "dashboards#seller", as: :seller_dashboard
  get "dashboard/analytics", to: "dashboards#analytics", as: :analytics
  
  # === Product Feeds ===
  # These can be dynamically generated by the controller or served as static files
  # To generate static files, run: rails feeds:generate
  # Then access them directly from /public/
  get "/merchant_feed.csv",      to: "feeds#feed",           as: :merchant_feed_csv
  get "/feeds/google_merchant",  to: "feeds#google_merchant", format: "xml", as: :google_merchant_feed
  get "/feeds/products.json",    to: "feeds#json_feed",       format: "json", as: :json_feed



  resource :cart, only: [:show] do
    post 'add',    to: 'carts#add'
    post 'remove', to: 'carts#remove'
    post 'clear',  to: 'carts#clear'
    post 'update', to: 'carts#update', as: :update
  end

  # === Webhooks ===
  post "/dhl/webhook", to: "webhooks#dhl"

  # === Static Pages ===
  root "pages#home"
  get "about",         to: "pages#about"
  get "contact",       to: "pages#contact"
  get "return-policy", to: "pages#return_policy"

  # === ActiveStorage ===
  mount ActiveStorage::Engine => "/rails/active_storage"

  # === Health check ===
  get "up" => "rails/health#show", as: :rails_health_check
end
