require "active_support/core_ext/integer/time"

Rails.application.configure do
  # ✅ Use Supabase for Active Storage
  config.active_storage.service = :supabase

  # ✅ Host for ActiveStorage signed URLs
  config.action_controller.default_url_options = {
    host: "shipping-and-logistic.onrender.com",
    protocol: "https"
  }

  # ✅ Ensure URLs generated by ActiveStorage use the correct host
  routes.default_url_options[:host] = "shipping-and-logistic.onrender.com"

  # ✅ Secret key fallback
  config.secret_key_base = ENV["SECRET_KEY_BASE"] || Rails.application.credentials.secret_key_base

  # ✅ Serve static assets (for CSS, JS, images, etc.)
  config.public_file_server.enabled = ENV["RAILS_SERVE_STATIC_FILES"].present? || true
  config.public_file_server.headers = {
    "Cache-Control" => "public, max-age=#{1.year.to_i}"
  }

  # ✅ Performance settings
  config.enable_reloading = false
  config.eager_load = true
  config.action_controller.perform_caching = true

  # ✅ Error pages
  config.consider_all_requests_local = false

  # ✅ SSL (important for Render & Supabase)
  config.force_ssl = true
  config.assume_ssl = true

  # ✅ Logging (for Render logs)
  config.log_tags = [:request_id]
  config.log_level = ENV.fetch("RAILS_LOG_LEVEL", "info")
  config.logger = ActiveSupport::TaggedLogging.new(Logger.new(STDOUT))

  # ✅ Optionally log to file (useful for debugging locally)
  if Rails.env.production?
    file_logger = Logger.new(Rails.root.join("log/production.log"))
    file_logger.level = Logger::DEBUG
    config.logger.extend(ActiveSupport::Logger.broadcast(file_logger))
  end

  # ✅ Healthcheck (Render-friendly)
  config.silence_healthcheck_path = "/up"

  # ✅ Active Record settings
  config.active_record.dump_schema_after_migration = false
  config.active_support.report_deprecations = false
  config.active_record.attributes_for_inspect = [:id]

  # ✅ I18n fallback
  config.i18n.fallbacks = true

  # ✅ Mailer host (for Devise, if used)
  config.action_mailer.default_url_options = {
    host: "shipping-and-logistic.onrender.com",
    protocol: "https"
  }

  # ✅ Allow image URLs to be served directly
  config.active_storage.resolve_model_to_route = :rails_storage_proxy
end
